name: Tests

on:
    push: null

jobs:
    tests:
        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.1
                    coverage: none

            -   uses: "ramsey/composer-install@v1"

            -   run: vendor/bin/phpunit
